# Generated by Django 2.1.8 on 2019-06-06 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('bonus', models.CharField(max_length=50)),
                ('datereg', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avtor', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=50)),
                ('articul', models.CharField(max_length=50)),
                ('PG', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('pages', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('mass', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=150)),
                ('OGRN', models.CharField(max_length=50)),
                ('INN', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=50)),
                ('maxcap', models.IntegerField()),
                ('item', models.ManyToManyField(related_name='TransferAuto', to='shop.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Seller'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='item',
            field=models.ManyToManyField(related_name='DealAuto', to='shop.Item'),
        ),
    ]
