# Generated by Django 2.1.8 on 2019-06-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190606_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsForBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsInStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='buyer',
            name='item',
            field=models.ManyToManyField(to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.ManyToManyField(to='shop.Item'),
        ),
        migrations.AddField(
            model_name='itemsinstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Stock'),
        ),
        migrations.AddField(
            model_name='itemsforbuyer',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Buyer'),
        ),
    ]
