# Generated by Django 2.1.8 on 2019-06-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190606_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item',
        ),
    ]
