# Generated by Django 2.1.8 on 2019-06-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190606_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsforbuyer',
            old_name='stock',
            new_name='buyer',
        ),
    ]
