# Generated by Django 2.1.8 on 2019-06-06 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190606_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsforbuyer',
            name='datereg',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsinstock',
            name='datereg',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
